# 소셜 로그인 아닐 때 회원가입
USER_REGISTER_NO_SOCIAL_LOGIN_QUERY = """
INSERT INTO USERS.USER(
    USER_EMAIL, USER_SOCIAL_YN, USER_AUTH_TYPE, USER_TOKEN, USER_SOCIAL_ID
  , USER_PW, USER_NM, USER_TOKEN_EXPIRED_DTTM, CREATED_DTTM, UPDATED_DTTM
)
SELECT %(USER_EMAIL)s, 'N', 'NURU', '', ''
     , %(USER_PW)s, %(USER_NM)s, NULL, NOW(), NULL 
"""

# 로그인
USER_LOGIN_QUERY = """
SELECT *
  FROM USERS.USER
 WHERE USER_EMAIL = %(USER_EMAIL)s
   AND USER_PW = %(USER_PW)s
;
"""

USER_SOCIAL_ACCOUNT_QUERY = """
SELECT *
  FROM USERS.USER
  WHERE USER_SOCIAL_YN = %(USER_SOCIAL_YN)s
  AND USER_AUTH_TYPE = %(USER_AUTH_TYPE)s
  AND USER_SOCIAL_ID = %(USER_SOCIAL_ID)s
"""

USER_SOCIAL_REGISTER_QUERY = """
INSERT INTO USERS.USER(
    USER_EMAIL, USER_SOCIAL_YN, USER_AUTH_TYPE, USER_TOKEN, USER_SOCIAL_ID
  , USER_PW, USER_NM, USER_TOKEN_EXPIRED_DTTM, CREATED_DTTM, UPDATED_DTTM
)
SELECT %(USER_SOCIAL_ID)s, %(USER_SOCIAL_YN)s, %(USER_AUTH_TYPE)s, '', %(USER_SOCIAL_ID)s, '', '', NULL, NOW(), NULL
"""

USER_SOCIAL_LOGIN_QUERY = """
SELECT *
  FROM USERS.USER
  WHERE USER_SOICAL_TOKEN = %(USER_SOCIAL_ID)s
;
"""

USER_TOKEN_UPDATE_QUERY = """
UPDATE USERS.USER SET USER_TOKEN = %(USER_TOKEN)s, USER_TOKEN_EXPIRED_DTTM = %(USER_TOKEN_EXPIRED_DTTM)s, CREATED_DTTM = %(CREATED_DTTM)s
  WHERE USER_EMAIL = %(USER_EMAIL)s
"""
