# 소셜 로그인 아닐 때 회원가입
USER_REGISTER_NO_SOCIAL_LOGIN_QUERY = """
INSERT INTO USERS.USER(
    USER_EMAIL, USER_SOCIAL_YN, USER_AUTH_TYPE, USER_TOKEN, USER_SOCIAL_ID
  , USER_PW, USER_NM, USER_TOKEN_EXPIRED_DTTM, CREATED_DTTM, UPDATED_DTTM
)
SELECT %(USER_EMAIL)s, 'N', 'NURU', '', ''
     , %(USER_PW)s, %(USER_NM)s, NULL, NOW(), NULL 
"""

# 로그인
USER_LOGIN_QUERY = """
SELECT *
  FROM USERS.USER
 WHERE USER_EMAIL = %(USER_EMAIL)s
   AND USER_PW = %(USER_PW)s
;
"""

USER_REGISTER_SOCIAL_LOGIN_QUERY = """
INSERT INTO USERS.USER(
    USER_EMAIL, USER_SOCIAL_YN, USER_AUTH_TYPE, USER_TOKEN, USER_SOCIAL_ID
  , USER_PW, USER_NM, USER_TOKEN_EXPIRED_DTTM, CREATED_DTTM, UPDATED_DTTM
)
SELECT %(USER_EMAIL)s, 'Y', %(USER_AUTH_TYPE)s, %(USER_TOKEN)s, %(USER_SOCIAL_ID)s,
    '' , NULL, NULL, NOW(), NULL
;
"""

USER_SOCIAL_LOGIN_QUERY = """
SELECT *
  FROM USERS.USER
 WHERE USER_SOCIAL_YN = 'Y' AND
 USER_AUTH_TYPE = %(USER_AUTH_TYPE)s AND
 USER_TOKEN = %(USER_TOKEN)s
;
"""